// client/src/views/EnvironmentPage.vue
<template>
  <a-card title="环境管理" :bordered="false">
    <template #extra>
      <a-button type="primary" @click="openCreate">
        <plus-outlined />新建环境
      </a-button>
    </template>
    <a-table
      :data-source="envs"
      :columns="columns"
      row-key="id"
      :loading="loading"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'action'">
          <a-space>
            <a-button size="small" type="link" @click="openEdit(record)">编辑</a-button>
            <a-popconfirm title="确认删除？" @confirm="remove(record)">
              <a-button size="small" type="link" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>

    <a-modal
      v-model:open="modal"
      :title="form.id ? '编辑环境' : '新建环境'"
      @ok="save"
      width="680"
    >
      <a-form layout="vertical">
        <a-row :gutter="12">
          <a-col :span="12">
            <a-form-item label="名称" required>
              <a-input v-model:value="form.name" placeholder="如 开发 / 测试 / 生产" />
            </a-form-item>
          </a-col>
          <a-col :span="12">
            <a-form-item label="BaseURL">
              <a-input v-model:value="form.baseUrl" placeholder="https://api.example.com" />
            </a-form-item>
          </a-col>
        </a-row>
        <a-form-item label="公共 Header">
          <KeyValueEditor v-model="form.headers" />
        </a-form-item>
        <a-form-item label="公共变量">
          <KeyValueEditor v-model="form.variables" />
        </a-form-item>
      </a-form>
    </a-modal>
  </a-card>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { message } from 'ant-design-vue'
import { PlusOutlined } from '@ant-design/icons-vue'
import { EnvironmentApi } from '@/api'
import { useProjectStore } from '@/stores/project'
import type { Environment, KeyValueItem } from '@/types'
import KeyValueEditor from '@/components/KeyValueEditor.vue'

const projectStore = useProjectStore()
const projectId = computed(() => projectStore.currentProjectId)

const envs = ref<Environment[]>([])
const loading = ref(false)
const modal = ref(false)
const form = reactive<Partial<Environment>>({
  name: '',
  baseUrl: '',
  headers: [],
  variables: []
})

const columns = [
  { title: '名称', dataIndex: 'name' },
  { title: 'BaseURL', dataIndex: 'baseUrl', ellipsis: true },
  { title: '公共 Header', key: 'headerCount', width: 100, customRender: ({ record }: any) => record.headers?.length || 0 },
  { title: '公共变量', key: 'varCount', width: 100, customRender: ({ record }: any) => record.variables?.length || 0 },
  { title: '操作', key: 'action', width: 140 }
]

async function reload() {
  if (!projectId.value) return
  loading.value = true
  try {
    envs.value = await EnvironmentApi.list(projectId.value)
  } finally {
    loading.value = false
  }
}

function openCreate() {
  Object.assign(form, {
    id: undefined,
    name: '',
    baseUrl: '',
    headers: [] as KeyValueItem[],
    variables: [] as KeyValueItem[]
  })
  modal.value = true
}

function openEdit(record: Environment) {
  Object.assign(form, record)
  modal.value = true
}

async function save() {
  if (!form.name) {
    message.warning('请填写名称')
    return
  }
  const payload = { ...form, projectId: projectId.value }
  if (form.id) {
    await EnvironmentApi.update(form.id, form)
  } else {
    await EnvironmentApi.create(payload)
  }
  message.success('已保存')
  modal.value = false
  await reload()
}

async function remove(record: Environment) {
  await EnvironmentApi.remove(record.id)
  await reload()
}

watch(projectId, reload, { immediate: false })
onMounted(reload)
</script>

// client/src/pages/EnvironmentPage.tsx
import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, Modal, Popconfirm, Space, Table, Tag, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useParams } from 'react-router-dom'
import { api, getErrorMessage } from '../api/client'
import type { Environment } from '../api/types'
import KeyValueEditor from '../components/KeyValueEditor'

export default function EnvironmentPage() {
  const { projectId } = useParams<{ projectId: string }>()
  const [envs, setEnvs] = useState<Environment[]>([])
  const [loading, setLoading] = useState(false)
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<Environment | null>(null)
  const [form] = Form.useForm()

  const load = async () => {
    setLoading(true)
    try {
      setEnvs(await api.listEnvironments(projectId!))
    } catch (e) {
      message.error(getErrorMessage(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId])

  const handleSubmit = async () => {
    const values = await form.validateFields()
    const payload = {
      name: values.name,
      baseUrl: values.baseUrl ?? '',
      variables: values.variables ?? [],
      headers: values.headers ?? [],
    }
    try {
      if (editing) await api.updateEnvironment(editing.id, payload)
      else await api.createEnvironment(projectId!, payload)
      message.success('保存成功')
      setOpen(false)
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const handleDelete = async (id: string) => {
    try {
      await api.deleteEnvironment(id)
      message.success('删除成功')
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const columns: ColumnsType<Environment> = [
    { title: '名称', dataIndex: 'name' },
    { title: 'Base URL', dataIndex: 'baseUrl' },
    {
      title: '变量',
      dataIndex: 'variables',
      render: (v: Environment['variables']) => (
        <Space wrap>
          {(v ?? []).map((kv) => (
            <Tag key={kv.key}>
              {kv.key}={kv.value}
            </Tag>
          ))}
        </Space>
      ),
    },
    {
      title: '操作',
      render: (_, record) => (
        <Space>
          <Button
            size="small"
            type="link"
            onClick={() => {
              setEditing(record)
              form.setFieldsValue({
                name: record.name,
                baseUrl: record.baseUrl,
                variables: record.variables ?? [],
                headers: record.headers ?? [],
              })
              setOpen(true)
            }}
          >
            编辑
          </Button>
          <Popconfirm title="确认删除该环境？" onConfirm={() => handleDelete(record.id)}>
            <Button size="small" type="link" danger>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <Card
      title="环境管理"
      extra={
        <Button
          type="primary"
          onClick={() => {
            setEditing(null)
            form.resetFields()
            setOpen(true)
          }}
        >
          新建环境
        </Button>
      }
    >
      <Table rowKey="id" loading={loading} columns={columns} dataSource={envs} />
      <Modal
        title={editing ? '编辑环境' : '新建环境'}
        open={open}
        onOk={handleSubmit}
        onCancel={() => setOpen(false)}
        width={720}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item name="name" label="名称" rules={[{ required: true, message: '请输入名称' }]}>
            <Input placeholder="如：dev / test / prod" />
          </Form.Item>
          <Form.Item name="baseUrl" label="Base URL">
            <Input placeholder="如：http://127.0.0.1:8080" />
          </Form.Item>
          <KeyValueEditor name="variables" label="变量" keyPlaceholder="变量名" valuePlaceholder="变量值" />
          <div style={{ height: 16 }} />
          <KeyValueEditor name="headers" label="公共请求头" keyPlaceholder="Header 名" />
        </Form>
      </Modal>
    </Card>
  )
}
