// client/src/views/ProjectList.vue
<template>
  <a-card title="项目列表" :bordered="false">
    <template #extra>
      <a-space>
        <a-input-search
          v-model:value="keyword"
          placeholder="按名称搜索"
          style="width: 220px"
          @search="reload"
          @pressEnter="reload"
        />
        <a-button type="primary" @click="openModal()">
          <plus-outlined /> 新建项目
        </a-button>
      </a-space>
    </template>
    <a-table
      :data-source="projects"
      :columns="columns"
      row-key="id"
      :loading="loading"
      :pagination="{ pageSize: 20 }"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'updatedAt'">
          {{ formatTime(record.updatedAt) }}
        </template>
        <template v-else-if="column.key === 'action'">
          <a-space>
            <a-button size="small" type="link" @click="enterProject(record)">
              <enter-outlined />进入
            </a-button>
            <a-button size="small" type="link" @click="openModal(record)">
              编辑
            </a-button>
            <a-popconfirm
              title="确认删除该项目及其下属数据？"
              @confirm="remove(record)"
            >
              <a-button size="small" type="link" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>
  </a-card>

  <a-modal
    v-model:open="modal"
    :title="editing.id ? '编辑项目' : '新建项目'"
    @ok="save"
    :confirm-loading="saving"
    width="520"
  >
    <a-form layout="vertical">
      <a-form-item label="项目名称" required>
        <a-input v-model:value="editing.name" placeholder="例如 电商主站" />
      </a-form-item>
      <a-form-item label="描述">
        <a-textarea
          v-model:value="editing.description"
          :auto-size="{ minRows: 2, maxRows: 5 }"
        />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { PlusOutlined, EnterOutlined } from '@ant-design/icons-vue'
import dayjs from 'dayjs'
import { ProjectApi } from '@/api'
import { useProjectStore } from '@/stores/project'
import type { Project } from '@/types'

const router = useRouter()
const projectStore = useProjectStore()

const keyword = ref('')
const projects = ref<Project[]>([])
const loading = ref(false)
const modal = ref(false)
const saving = ref(false)
const editing = reactive<Partial<Project>>({ name: '', description: '' })

const columns = [
  { title: '名称', dataIndex: 'name' },
  { title: '描述', dataIndex: 'description', ellipsis: true },
  { title: '更新时间', key: 'updatedAt', width: 180 },
  { title: '操作', key: 'action', width: 200 }
]

function formatTime(iso: string) {
  return dayjs.utc(iso).local().format('YYYY-MM-DD HH:mm')
}

async function reload() {
  loading.value = true
  try {
    projects.value = await ProjectApi.list(keyword.value)
  } finally {
    loading.value = false
  }
}

function openModal(record?: Project) {
  if (record) {
    Object.assign(editing, record)
  } else {
    Object.assign(editing, { id: undefined, name: '', description: '' })
  }
  modal.value = true
}

async function save() {
  if (!editing.name) {
    message.warning('请填写项目名称')
    return
  }
  saving.value = true
  try {
    if (editing.id) {
      await ProjectApi.update(editing.id!, editing)
      message.success('已保存')
    } else {
      await ProjectApi.create(editing)
      message.success('已创建')
    }
    modal.value = false
    await reload()
    await projectStore.fetchAll()
  } finally {
    saving.value = false
  }
}

async function remove(record: Project) {
  await ProjectApi.remove(record.id)
  message.success('已删除')
  await reload()
  await projectStore.fetchAll()
}

function enterProject(record: Project) {
  projectStore.switchProject(record.id)
  router.push({ name: 'workbench' })
}

onMounted(reload)
</script>

// client/src/pages/ProjectList.tsx
import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, Modal, Popconfirm, Space, Table, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useNavigate } from 'react-router-dom'
import { api, getErrorMessage } from '../api/client'
import type { Project } from '../api/types'

export default function ProjectList() {
  const [projects, setProjects] = useState<Project[]>([])
  const [loading, setLoading] = useState(false)
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<Project | null>(null)
  const [form] = Form.useForm()
  const navigate = useNavigate()

  const load = async () => {
    setLoading(true)
    try {
      setProjects(await api.listProjects())
    } catch (e) {
      message.error(getErrorMessage(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load()
  }, [])

  const handleSubmit = async () => {
    const values = await form.validateFields()
    try {
      if (editing) await api.updateProject(editing.id, values)
      else await api.createProject(values)
      message.success('保存成功')
      setOpen(false)
      form.resetFields()
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const handleDelete = async (id: string) => {
    try {
      await api.deleteProject(id)
      message.success('删除成功')
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const columns: ColumnsType<Project> = [
    { title: '名称', dataIndex: 'name' },
    { title: '描述', dataIndex: 'description' },
    {
      title: '创建时间',
      dataIndex: 'createdAt',
      render: (v: string) => new Date(v).toLocaleString(),
    },
    {
      title: '操作',
      render: (_, record) => (
        <Space>
          <Button size="small" type="link" onClick={() => navigate(`/projects/${record.id}/apis`)}>
            进入
          </Button>
          <Button
            size="small"
            type="link"
            onClick={() => {
              setEditing(record)
              form.setFieldsValue(record)
              setOpen(true)
            }}
          >
            编辑
          </Button>
          <Popconfirm title="确认删除该项目？" onConfirm={() => handleDelete(record.id)}>
            <Button size="small" type="link" danger>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <Card
      title="项目列表"
      extra={
        <Button
          type="primary"
          onClick={() => {
            setEditing(null)
            form.resetFields()
            setOpen(true)
          }}
        >
          新建项目
        </Button>
      }
    >
      <Table rowKey="id" loading={loading} columns={columns} dataSource={projects} />
      <Modal
        title={editing ? '编辑项目' : '新建项目'}
        open={open}
        onOk={handleSubmit}
        onCancel={() => setOpen(false)}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item name="name" label="名称" rules={[{ required: true, message: '请输入名称' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="description" label="描述">
            <Input.TextArea rows={3} />
          </Form.Item>
        </Form>
      </Modal>
    </Card>
  )
}
