// client/src/views/UserManagement.vue
<template>
  <a-card title="用户管理" :bordered="false">
    <template #extra>
      <a-button type="primary" @click="openCreate"><plus-outlined />新建用户</a-button>
    </template>
    <a-table :data-source="users" :columns="columns" row-key="id" :loading="loading">
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'role'">
          <a-tag :color="record.role === 'admin' ? 'red' : 'blue'">{{ record.role }}</a-tag>
        </template>
        <template v-else-if="column.key === 'action'">
          <a-space>
            <a-button size="small" type="link" @click="openEdit(record)">编辑</a-button>
            <a-popconfirm title="确认删除？" @confirm="remove(record)">
              <a-button size="small" type="link" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>

    <a-modal v-model:open="modal" :title="form.id ? '编辑用户' : '新建用户'" @ok="save" width="480">
      <a-form layout="vertical">
        <a-form-item label="用户名" required>
          <a-input v-model:value="form.username" :disabled="!!form.id" />
        </a-form-item>
        <a-form-item v-if="!form.id" label="初始密码" required>
          <a-input-password v-model:value="form.password" placeholder="至少 6 位" />
        </a-form-item>
        <a-form-item v-else label="重置密码（留空保持不变）">
          <a-input-password v-model:value="form.password" />
        </a-form-item>
        <a-form-item label="角色">
          <a-select v-model:value="form.role" :options="roleOptions" />
        </a-form-item>
      </a-form>
    </a-modal>
  </a-card>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { message } from 'ant-design-vue'
import { PlusOutlined } from '@ant-design/icons-vue'
import { UserApi } from '@/api'
import type { User } from '@/types'

const users = ref<User[]>([])
const loading = ref(false)
const modal = ref(false)
const form = reactive<{ id?: string; username: string; password: string; role: string }>({
  username: '',
  password: '',
  role: 'member'
})

const columns = [
  { title: '用户名', dataIndex: 'username' },
  { title: '角色', key: 'role', width: 100 },
  { title: '创建时间', dataIndex: 'createdAt' },
  { title: '操作', key: 'action', width: 140 }
]

const roleOptions = [
  { value: 'admin', label: '管理员' },
  { value: 'member', label: '成员' },
  { value: 'viewer', label: '查看者' }
]

async function reload() {
  loading.value = true
  try {
    users.value = await UserApi.list()
  } finally {
    loading.value = false
  }
}

function openCreate() {
  Object.assign(form, { id: undefined, username: '', password: '', role: 'member' })
  modal.value = true
}

function openEdit(record: User) {
  Object.assign(form, { id: record.id, username: record.username, password: '', role: record.role })
  modal.value = true
}

async function save() {
  if (!form.username) {
    message.warning('请填写用户名')
    return
  }
  if (!form.id && form.password.length < 6) {
    message.warning('初始密码至少 6 位')
    return
  }
  if (form.id) {
    await UserApi.update(form.id, { role: form.role, password: form.password || undefined })
  } else {
    await UserApi.create({ username: form.username, password: form.password, role: form.role })
  }
  message.success('已保存')
  modal.value = false
  await reload()
}

async function remove(record: User) {
  await UserApi.remove(record.id)
  await reload()
}

onMounted(reload)
</script>

// client/src/pages/UserManagement.tsx
/**
 * 用户管理页：用户列表 + 新增 / 编辑 / 删除 / 重置密码。
 */
import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Table, Tag, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { api, getErrorMessage } from '../api/client'
import type { User } from '../api/types'

export default function UserManagement() {
  const [users, setUsers] = useState<User[]>([])
  const [loading, setLoading] = useState(false)

  // 新增/编辑弹窗
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<User | null>(null)
  const [form] = Form.useForm()

  // 重置密码弹窗
  const [pwdOpen, setPwdOpen] = useState(false)
  const [pwdUser, setPwdUser] = useState<User | null>(null)
  const [pwdForm] = Form.useForm()

  const load = async () => {
    setLoading(true)
    try {
      setUsers(await api.listUsers())
    } catch (e) {
      message.error(getErrorMessage(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load()
  }, [])

  // 新增或编辑用户
  const handleSubmit = async () => {
    const values = await form.validateFields()
    try {
      if (editing) {
        await api.updateUser(editing.id, { username: values.username, role: values.role })
      } else {
        await api.createUser({
          username: values.username,
          password: values.password,
          role: values.role,
        })
      }
      message.success('保存成功')
      setOpen(false)
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  // 删除用户
  const handleDelete = async (id: string) => {
    try {
      await api.deleteUser(id)
      message.success('删除成功')
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  // 重置密码
  const handleResetPassword = async () => {
    const values = await pwdForm.validateFields()
    try {
      await api.resetUserPassword(pwdUser!.id, values.newPassword)
      message.success('密码已重置')
      setPwdOpen(false)
      pwdForm.resetFields()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const columns: ColumnsType<User> = [
    { title: '用户名', dataIndex: 'username' },
    {
      title: '角色',
      dataIndex: 'role',
      render: (r: string) => {
        const color = r === 'admin' ? 'blue' : r === 'member' ? 'green' : 'default'
        const label = r === 'admin' ? '管理员' : r === 'member' ? '成员' : '查看者'
        return <Tag color={color}>{label}</Tag>
      },
    },
    {
      title: '创建时间',
      dataIndex: 'createdAt',
      render: (v: string) => new Date(v).toLocaleString(),
    },
    {
      title: '操作',
      render: (_, record) => (
        <Space>
          <Button
            size="small"
            type="link"
            onClick={() => {
              setEditing(record)
              form.setFieldsValue({ username: record.username, role: record.role })
              setOpen(true)
            }}
          >
            编辑
          </Button>
          <Button
            size="small"
            type="link"
            onClick={() => {
              setPwdUser(record)
              pwdForm.resetFields()
              setPwdOpen(true)
            }}
          >
            改密码
          </Button>
          <Popconfirm title="确认删除该用户？" onConfirm={() => handleDelete(record.id)}>
            <Button size="small" type="link" danger>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <Card
      title="用户管理"
      extra={
        <Button
          type="primary"
          onClick={() => {
            setEditing(null)
            form.resetFields()
            setOpen(true)
          }}
        >
          新增用户
        </Button>
      }
    >
      <Table rowKey="id" loading={loading} columns={columns} dataSource={users} />

      {/* 新增/编辑用户 */}
      <Modal
        title={editing ? '编辑用户' : '新增用户'}
        open={open}
        onOk={handleSubmit}
        onCancel={() => setOpen(false)}
        destroyOnHidden
      >
        <Form form={form} layout="vertical">
          <Form.Item name="username" label="用户名" rules={[{ required: true, message: '请输入用户名' }]}>
            <Input />
          </Form.Item>
          {!editing && (
            <Form.Item name="password" label="密码" rules={[{ required: true, message: '请输入密码' }]}>
              <Input.Password />
            </Form.Item>
          )}
          <Form.Item name="role" label="角色" initialValue="admin">
            <Select
              options={[
                { value: 'admin', label: '管理员' },
                { value: 'member', label: '成员' },
                { value: 'viewer', label: '查看者' },
              ]}
            />
          </Form.Item>
        </Form>
      </Modal>

      {/* 重置密码 */}
      <Modal
        title={`重置密码：${pwdUser?.username ?? ''}`}
        open={pwdOpen}
        onOk={handleResetPassword}
        onCancel={() => setPwdOpen(false)}
        destroyOnHidden
      >
        <Form form={pwdForm} layout="vertical">
          <Form.Item
            name="newPassword"
            label="新密码"
            rules={[{ required: true, message: '请输入新密码' }]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>
    </Card>
  )
}
