// client/src/pages/ScenarioList.tsx
import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, Modal, Popconfirm, Space, Table, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useNavigate, useParams } from 'react-router-dom'
import { api, getErrorMessage } from '../api/client'
import type { Scenario } from '../api/types'

export default function ScenarioList() {
  const { projectId } = useParams<{ projectId: string }>()
  const [scenarios, setScenarios] = useState<Scenario[]>([])
  const [loading, setLoading] = useState(false)
  const [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<Scenario | null>(null)
  const [form] = Form.useForm()
  const navigate = useNavigate()

  const load = async () => {
    setLoading(true)
    try {
      setScenarios(await api.listScenarios(projectId!))
    } catch (e) {
      message.error(getErrorMessage(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId])

  const handleSubmit = async () => {
    const values = await form.validateFields()
    try {
      if (editing) await api.updateScenario(editing.id, values)
      else await api.createScenario(projectId!, values)
      message.success('保存成功')
      setOpen(false)
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const handleDelete = async (id: string) => {
    try {
      await api.deleteScenario(id)
      message.success('删除成功')
      load()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const columns: ColumnsType<Scenario> = [
    { title: '名称', dataIndex: 'name' },
    { title: '描述', dataIndex: 'description' },
    {
      title: '操作',
      render: (_, record) => (
        <Space>
          <Button
            size="small"
            type="link"
            onClick={() => navigate(`/projects/${projectId}/scenarios/${record.id}`)}
          >
            编排
          </Button>
          <Button
            size="small"
            type="link"
            onClick={() => {
              setEditing(record)
              form.setFieldsValue(record)
              setOpen(true)
            }}
          >
            编辑
          </Button>
          <Popconfirm title="确认删除该场景？" onConfirm={() => handleDelete(record.id)}>
            <Button size="small" type="link" danger>
              删除
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <Card
      title="场景自动化"
      extra={
        <Button
          type="primary"
          onClick={() => {
            setEditing(null)
            form.resetFields()
            setOpen(true)
          }}
        >
          新建场景
        </Button>
      }
    >
      <Table rowKey="id" loading={loading} columns={columns} dataSource={scenarios} />
      <Modal
        title={editing ? '编辑场景' : '新建场景'}
        open={open}
        onOk={handleSubmit}
        onCancel={() => setOpen(false)}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item name="name" label="名称" rules={[{ required: true, message: '请输入名称' }]}>
            <Input />
          </Form.Item>
          <Form.Item name="description" label="描述">
            <Input.TextArea rows={3} />
          </Form.Item>
        </Form>
      </Modal>
    </Card>
  )
}

// client/src/views/ScenarioList.vue
<template>
  <a-card title="接口场景" :bordered="false">
    <template #extra>
      <a-button type="primary" @click="openCreate">
        <plus-outlined />新建场景
      </a-button>
    </template>
    <a-table
      :data-source="scenarios"
      :columns="columns"
      row-key="id"
      :loading="loading"
      @row-click="(r: any) => router.push({ name: 'scenario-editor', params: { id: r.id } })"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'action'">
          <a-space @click.stop>
            <a-button size="small" type="link" @click="execute(record)">
              <play-circle-outlined />执行
            </a-button>
            <a-popconfirm title="确认删除？" @confirm="remove(record)">
              <a-button size="small" type="link" danger>删除</a-button>
            </a-popconfirm>
          </a-space>
        </template>
      </template>
    </a-table>

    <a-modal
      v-model:open="modal"
      title="新建场景"
      @ok="save"
      width="480"
    >
      <a-form layout="vertical">
        <a-form-item label="名称" required>
          <a-input v-model:value="form.name" />
        </a-form-item>
        <a-form-item label="描述">
          <a-textarea v-model:value="form.description" :auto-size="{ minRows: 1, maxRows: 3 }" />
        </a-form-item>
      </a-form>
    </a-modal>
  </a-card>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { PlusOutlined, PlayCircleOutlined } from '@ant-design/icons-vue'
import { ScenarioApi } from '@/api'
import { useProjectStore } from '@/stores/project'
import type { Scenario } from '@/types'

const router = useRouter()
const projectStore = useProjectStore()
const projectId = computed(() => projectStore.currentProjectId)

const scenarios = ref<Scenario[]>([])
const loading = ref(false)
const modal = ref(false)
const form = reactive<Partial<Scenario>>({ name: '', description: '' })

const columns = [
  { title: '名称', dataIndex: 'name' },
  { title: '描述', dataIndex: 'description', ellipsis: true },
  { title: '更新时间', dataIndex: 'updatedAt' },
  { title: '操作', key: 'action', width: 140 }
]

async function reload() {
  if (!projectId.value) return
  loading.value = true
  try {
    scenarios.value = await ScenarioApi.list(projectId.value)
  } finally {
    loading.value = false
  }
}

function openCreate() {
  Object.assign(form, { id: undefined, name: '', description: '' })
  modal.value = true
}

async function save() {
  if (!form.name) {
    message.warning('请填写名称')
    return
  }
  const created = await ScenarioApi.create({
    ...form,
    projectId: projectId.value,
    steps: []
  })
  modal.value = false
  router.push({ name: 'scenario-editor', params: { id: created.id } })
}

async function execute(record: Scenario) {
  const r = await ScenarioApi.execute(record.id)
  message.success(`执行完成：${r.status}`)
}

async function remove(record: Scenario) {
  await ScenarioApi.remove(record.id)
  await reload()
}

watch(projectId, reload, { immediate: false })
onMounted(reload)
</script>
