// client/src/pages/UiReportList.tsx
/**
 * UI 自动化测试报告页：展示 UI 测试执行报告（独立于接口测试报告）。
 */
import { useEffect, useState } from 'react'
import { Alert, Card, Space, Table, Tag, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useParams } from 'react-router-dom'
import { api, getErrorMessage } from '../api/client'
import type { UiReport } from '../api/types'

const STATUS_COLOR: Record<string, string> = { PASS: 'green', FAIL: 'red', ERROR: 'orange' }

export default function UiReportList() {
  const { projectId } = useParams<{ projectId: string }>()
  const [reports, setReports] = useState<UiReport[]>([])
  const [loading, setLoading] = useState(false)

  const load = async () => {
    setLoading(true)
    try {
      setReports(await api.listUiReports(projectId!))
    } catch (e) {
      message.error(getErrorMessage(e))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId])

  const columns: ColumnsType<UiReport> = [
    { title: '用例名称', dataIndex: 'name' },
    {
      title: '结果',
      dataIndex: 'status',
      render: (s: string) => <Tag color={STATUS_COLOR[s]}>{s}</Tag>,
    },
    { title: '耗时', dataIndex: 'duration', render: (v: number) => `${v}ms` },
    {
      title: '执行时间',
      dataIndex: 'startedAt',
      render: (v: string) => new Date(v).toLocaleString(),
    },
  ]

  return (
    <Card title="UI 测试报告">
      <Table
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={reports}
        expandable={{
          expandedRowRender: (report) => (
            <div>
              {(report.details ?? []).map((d, i) => (
                <Card
                  key={i}
                  size="small"
                  title={
                    <Space>
                      <span>
                        步骤 {i + 1}：{d.action}
                        {d.target ? `（${d.target}）` : ''}
                      </span>
                      <Tag color={STATUS_COLOR[d.status]}>{d.status}</Tag>
                    </Space>
                  }
                  style={{ marginBottom: 8 }}
                >
                  <Alert
                    type={d.status === 'PASS' ? 'success' : 'error'}
                    showIcon
                    message={d.message}
                    style={{ marginBottom: 8 }}
                  />
                  {d.screenshot && (
                    <img
                      src={`data:image/png;base64,${d.screenshot}`}
                      alt="失败截图"
                      style={{ maxWidth: '100%', border: '1px solid #eee' }}
                    />
                  )}
                </Card>
              ))}
            </div>
          ),
        }}
      />
    </Card>
  )
}

// client/src/views/UiReportList.vue
<template>
  <a-card title="UI 自动化报告" :bordered="false">
    <a-table
      :data-source="reports"
      :columns="columns"
      row-key="id"
      :loading="loading"
    >
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'status'">
          <a-tag :color="statusColor(record.status)">{{ record.status }}</a-tag>
        </template>
        <template v-else-if="column.key === 'duration'">
          {{ record.duration }} ms
        </template>
        <template v-else-if="column.key === 'action'">
          <a-button size="small" type="link" @click="showDetail(record)">查看</a-button>
        </template>
      </template>
    </a-table>

    <a-modal v-model:open="detailOpen" title="报告明细" width="900" :footer="null">
      <a-tabs v-model:active-key="detailTab">
        <a-tab-pane key="steps" tab="步骤明细">
          <a-list :data-source="(currentReport?.details as any[]) || []">
            <template #renderItem="{ item }">
              <a-list-item>
                <a-space direction="vertical" style="width: 100%">
                  <a-space>
                    <a-tag :color="statusColor(item.status)">{{ item.status }}</a-tag>
                    <strong>{{ item.segment }} / {{ item.step?.name || '步骤' }}</strong>
                    <span style="color: #999">{{ item.durationMs }} ms</span>
                  </a-space>
                  <a-alert v-if="item.message" type="error" :message="item.message" />
                  <a-image
                    v-if="item.screenshot"
                    :width="320"
                    :src="`data:image/png;base64,${item.screenshot}`"
                  />
                </a-space>
              </a-list-item>
            </template>
          </a-list>
        </a-tab-pane>
        <a-tab-pane key="raw" tab="原始数据">
          <pre style="max-height: 500px; overflow: auto">{{ JSON.stringify(currentReport, null, 2) }}</pre>
        </a-tab-pane>
      </a-tabs>
    </a-modal>
  </a-card>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { UiApi } from '@/api'
import { useProjectStore } from '@/stores/project'
import type { UiReport } from '@/types'

const projectStore = useProjectStore()
const projectId = computed(() => projectStore.currentProjectId)

const reports = ref<UiReport[]>([])
const loading = ref(false)
const detailOpen = ref(false)
const detailTab = ref('steps')
const currentReport = ref<UiReport | null>(null)

const columns = [
  { title: '名称', dataIndex: 'name' },
  { title: '状态', key: 'status', width: 100 },
  { title: '耗时', key: 'duration', width: 100 },
  { title: '开始时间', dataIndex: 'startedAt', width: 180 },
  { title: '操作', key: 'action', width: 100 }
]

function statusColor(s: string) {
  return s === 'success' ? 'green' : s === 'failed' ? 'orange' : 'red'
}

async function reload() {
  if (!projectId.value) return
  loading.value = true
  try {
    reports.value = await UiApi.listReports(projectId.value)
  } finally {
    loading.value = false
  }
}

async function showDetail(record: UiReport) {
  currentReport.value = await UiApi.getReport(record.id)
  detailOpen.value = true
}

watch(projectId, reload, { immediate: false })
onMounted(reload)
</script>
