// client/src/layouts/AppLayout.vue
<template>
  <a-layout style="min-height: 100vh">
    <a-layout-header class="header">
      <div class="logo">⚡ Api-Web</div>
      <a-menu
        v-model:selectedKeys="selectedKeys"
        mode="horizontal"
        :items="menuItems"
        @select="onMenuSelect"
        style="flex: 1; min-width: 0"
      />
      <a-space>
        <a-select
          v-if="projectStore.projects.length > 0"
          :value="projectStore.currentProjectId"
          :options="projectOptions"
          style="width: 220px"
          @change="onProjectChange"
        />
        <a-dropdown>
          <a-space class="user-info">
            <a-avatar size="small">{{ auth.user?.username?.[0]?.toUpperCase() }}</a-avatar>
            <span>{{ auth.user?.username }}</span>
            <down-outlined />
          </a-space>
          <template #overlay>
            <a-menu>
              <a-menu-item @click="showChangePassword">
                <lock-outlined />修改密码
              </a-menu-item>
              <a-menu-divider />
              <a-menu-item @click="logout">
                <logout-outlined />退出登录
              </a-menu-item>
            </a-menu>
          </template>
        </a-dropdown>
      </a-space>
    </a-layout-header>
    <a-layout-content style="padding: 16px; background: #f0f2f5">
      <router-view v-slot="{ Component }">
        <component :is="Component" />
      </router-view>
    </a-layout-content>
  </a-layout>

  <a-modal
    v-model:open="passwordModal"
    title="修改密码"
    @ok="changePassword"
    :confirm-loading="changingPassword"
    width="420"
  >
    <a-form layout="vertical">
      <a-form-item label="原密码" required>
        <a-input-password v-model:value="passwordForm.oldPassword" />
      </a-form-item>
      <a-form-item label="新密码（至少 6 位）" required>
        <a-input-password v-model:value="passwordForm.newPassword" />
      </a-form-item>
    </a-form>
  </a-modal>
</template>

<script setup lang="ts">
import { computed, h, onMounted, ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { message } from 'ant-design-vue'
import {
  AppstoreOutlined, ProjectOutlined, CodeOutlined, ThunderboltOutlined,
  RobotOutlined, UserOutlined, FileTextOutlined, AuditOutlined, EnvironmentOutlined,
  SettingOutlined, DownOutlined, LockOutlined, LogoutOutlined
} from '@ant-design/icons-vue'
import { useAuthStore } from '@/stores/auth'
import { useProjectStore } from '@/stores/project'
import { AuthApi } from '@/api'

const router = useRouter()
const route = useRoute()
const auth = useAuthStore()
const projectStore = useProjectStore()

const selectedKeys = computed(() => [route.path.split('/')[1] || 'projects'])

const projectOptions = computed(() =>
  projectStore.projects.map((p) => ({ value: p.id, label: p.name }))
)

const menuItems = computed(() => [
  { key: 'projects', icon: () => h(ProjectOutlined), label: '项目' },
  { key: 'workbench', icon: () => h(AppstoreOutlined), label: '工作台' },
  { key: 'apis', icon: () => h(CodeOutlined), label: '接口管理' },
  { key: 'scenarios', icon: () => h(FileTextOutlined), label: '场景' },
  { key: 'tasks', icon: () => h(ThunderboltOutlined), label: '测试任务' },
  { key: 'reports', icon: () => h(FileTextOutlined), label: '接口报告' },
  { key: 'perf', icon: () => h(ThunderboltOutlined), label: '性能测试' },
  { key: 'ui', icon: () => h(RobotOutlined), label: 'UI 自动化' },
  { key: 'environments', icon: () => h(EnvironmentOutlined), label: '环境' },
  { key: 'environment-config', icon: () => h(SettingOutlined), label: '变量/模块' },
  ...(auth.isAdmin()
    ? [
        { key: 'users', icon: () => h(UserOutlined), label: '用户管理' },
        { key: 'audit-logs', icon: () => h(AuditOutlined), label: '审计日志' }
      ]
    : [])
])

function onMenuSelect({ key }: { key: string }) {
  router.push({ name: key })
}

function onProjectChange(id: string) {
  projectStore.switchProject(id)
  router.go(0)
}

function logout() {
  auth.logout()
  router.push({ name: 'login' })
}

const passwordModal = ref(false)
const changingPassword = ref(false)
const passwordForm = ref({ oldPassword: '', newPassword: '' })
function showChangePassword() {
  passwordForm.value = { oldPassword: '', newPassword: '' }
  passwordModal.value = true
}
async function changePassword() {
  if (!passwordForm.value.oldPassword || passwordForm.value.newPassword.length < 6) {
    message.warning('请填写完整；新密码至少 6 位')
    return
  }
  changingPassword.value = true
  try {
    await AuthApi.changePassword(passwordForm.value.oldPassword, passwordForm.value.newPassword)
    message.success('密码已修改')
    passwordModal.value = false
  } finally {
    changingPassword.value = false
  }
}

onMounted(async () => {
  await projectStore.fetchAll()
})
</script>

<style scoped>
.header {
  display: flex;
  align-items: center;
  background: #001529;
  padding: 0 24px;
  color: white;
}
.logo {
  font-size: 20px;
  font-weight: bold;
  margin-right: 32px;
  color: #fff;
}
.user-info {
  color: white;
  cursor: pointer;
}
</style>

// client/src/components/AppLayout.tsx
/**
 * 应用整体布局组件
 *
 * 职责：提供统一的页面框架——左侧导航（四个入口：接口自动化 / UI 自动化 / 环境配置 / 用户管理）+
 * 顶部栏（全局项目选择器 + 项目管理 + 当前用户下拉）+ 右侧内容区。
 */
import { useState } from 'react'
import { Dropdown, Form, Input, Layout, Menu, Modal, Select, message } from 'antd'
import type { MenuProps } from 'antd'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { clearAuth, getCurrentUser } from '../api/auth'
import { api, getErrorMessage } from '../api/client'
import { useProject } from '../context/ProjectContext'

const { Sider, Header, Content } = Layout

export default function AppLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const user = getCurrentUser()
  const { projects, projectId, setProjectId } = useProject()

  const [pwdOpen, setPwdOpen] = useState(false)
  const [pwdForm] = Form.useForm()

  const handleLogout = () => {
    clearAuth()
    navigate('/login')
  }

  const handleChangePassword = async () => {
    const values = await pwdForm.validateFields()
    try {
      await api.changePassword(values.oldPassword, values.newPassword)
      message.success('密码已修改，请重新登录')
      setPwdOpen(false)
      handleLogout()
    } catch (e) {
      message.error(getErrorMessage(e))
    }
  }

  const userMenuItems: MenuProps['items'] = [
    { key: 'password', label: '修改密码' },
    { type: 'divider' },
    { key: 'logout', label: '退出登录' },
  ]

  const onUserMenuClick: MenuProps['onClick'] = ({ key }) => {
    if (key === 'logout') handleLogout()
    if (key === 'password') {
      pwdForm.resetFields()
      setPwdOpen(true)
    }
  }

  // 侧边栏菜单：业务入口 + 管理员专属入口
  const isAdmin = user?.role === 'admin'
  const items: MenuProps['items'] = [
    {
      key: 'api-automation',
      label: '接口自动化',
      children: [
        {
          key: 'api-case',
          label: '接口用例',
          children: [
            { key: '/workbench', label: '工作台' },
          ],
        },
        { key: '/test-execution', label: '测试执行' },
        { key: '/test-reports', label: '测试报告' },
      ],
    },
    {
      key: 'ui-automation',
      label: 'UI 自动化',
      children: [
        { key: '/ui-tests', label: 'UI 用例' },
        { key: '/ui-scenarios', label: 'UI 用例执行' },
        { key: '/ui-reports', label: 'UI 测试报告' },
      ],
    },
    { key: '/environments', label: '环境配置' },
    // 系统管理入口仅管理员可见
    ...(isAdmin
      ? [
          { key: '/users', label: '用户管理' },
          { key: '/audit-logs', label: '审计日志' },
        ]
      : []),
  ]

  // 递归收集所有叶子路由 key（以 / 开头），用于最长前缀高亮
  const allKeys: string[] = []
  const collectKeys = (list: MenuProps['items']) => {
    for (const item of list ?? []) {
      if (item && 'children' in item && Array.isArray(item.children)) {
        collectKeys(item.children)
      } else if (item?.key) {
        allKeys.push(String(item.key))
      }
    }
  }
  collectKeys(items)
  const selectedKey = allKeys
    .filter((key) => location.pathname === key || location.pathname.startsWith(key + '/'))
    .sort((a, b) => b.length - a.length)[0]

  return (
    <Layout style={{ height: '100vh', overflow: 'hidden' }}>
      <Sider theme="dark" width={200}>
        <div
          style={{
            color: '#fff',
            padding: '16px 16px 12px',
            fontWeight: 600,
            fontSize: 16,
            whiteSpace: 'nowrap',
          }}
        >
          API 自动化平台
        </div>
        <Menu
          theme="dark"
          mode="inline"
          defaultOpenKeys={['api-automation', 'api-case', 'ui-automation']}
          selectedKeys={selectedKey ? [selectedKey] : []}
          items={items}
          onClick={({ key }) => {
            if (key.startsWith('/')) navigate(key)
          }}
        />
      </Sider>
      <Layout style={{ display: 'flex', flexDirection: 'column' }}>
        <Header
          style={{
            background: '#fff',
            padding: '0 16px',
            display: 'flex',
            alignItems: 'center',
            gap: 12,
            borderBottom: '1px solid #f0f0f0',
            height: 48,
            lineHeight: '48px',
          }}
        >
          <span style={{ color: '#999', fontSize: 13 }}>当前项目</span>
          <Select
            style={{ width: 200 }}
            size="small"
            placeholder="选择项目"
            value={projectId}
            options={projects.map((p) => ({ value: p.id, label: p.name }))}
            onChange={(v) => setProjectId(v)}
          />
          {isAdmin && (
            <span
              style={{ color: '#1677ff', fontSize: 13, cursor: 'pointer' }}
              onClick={() => navigate('/projects')}
            >
              项目管理
            </span>
          )}
          <div style={{ flex: 1 }} />
          <Dropdown menu={{ items: userMenuItems, onClick: onUserMenuClick }}>
            <span style={{ cursor: 'pointer', color: '#333' }}>{user?.username ?? ''}</span>
          </Dropdown>
        </Header>
        <Content style={{ flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
          <Outlet />
        </Content>
      </Layout>

      {/* 修改密码弹窗 */}
      <Modal
        title="修改密码"
        open={pwdOpen}
        onOk={handleChangePassword}
        onCancel={() => setPwdOpen(false)}
        destroyOnHidden
      >
        <Form form={pwdForm} layout="vertical">
          <Form.Item name="oldPassword" label="旧密码" rules={[{ required: true, message: '请输入旧密码' }]}>
            <Input.Password />
          </Form.Item>
          <Form.Item name="newPassword" label="新密码" rules={[{ required: true, message: '请输入新密码' }]}>
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>
    </Layout>
  )
}
